#!/usr/bin/env python3
"""Normalize C#'s committed PublicAPI snapshot into flat (type, member) rows.

``csharp/src/VerdictRules/PublicAPI.Shipped.txt`` and its sibling
``PublicAPI.Unshipped.txt`` are the two files
`Microsoft.CodeAnalysis.PublicApiAnalyzers
<https://github.com/dotnet/roslyn/blob/main/src/RoslynAnalyzers/PublicApiAnalyzers/PublicApiAnalyzers.Help.md>`_
tracks the package's public surface in -- one flat line per publicly visible
type or member, in the analyzer's own text format, generated by its RS0016
code fix and kept in sync by RS0016/RS0017 failing the build on drift.
``scripts/check_api_snapshots.py`` does not want to know that format -- it
wants one flat row per public symbol, the same shape every other language's
own extractor produces. This module is the only thing in the C# tree that
reads that format; everything downstream of :func:`extract_symbols` works
with plain dicts.

This module only *parses* the two committed files -- it never invokes
``dotnet build`` or the analyzer itself. Regenerating the snapshot (letting
the analyzer's own RS0016 code fix, or ``dotnet format analyzers
--diagnostics RS0016 --severity warn``, repopulate ``PublicAPI.Unshipped.txt``)
is a step a change to the public surface takes deliberately, the same way
updating a changelog is; this module does not paper over a stale snapshot by
re-running the tool behind the scenes.

PublicAPI.txt line shapes (see the analyzer's own README for the full
grammar):

- A blank line, or a ``#nullable enable``/``#nullable disable`` header --
  file bookkeeping, not a symbol.
- A ``*REMOVED*``-prefixed line -- a symbol Unshipped.txt records as having
  left the public surface since the last release. Not part of the *current*
  surface, so excluded here the same way the analyzer itself excludes it
  from what RS0016 considers currently declared.
- A type declaration: ``Namespace.TypeName`` or ``Namespace.TypeName<T>``
  for an open generic -- no ``->`` on the line, no further member.
- A member declaration: ``Namespace.TypeName.Member(params) -> ReturnType``
  for a method or constructor, or ``Namespace.TypeName.Member.get -> Type``
  / ``.set -> void`` for a property or indexer accessor. May carry a leading
  modifier token (``virtual``, ``override``, ``abstract``, ``static``,
  ``sealed``) and/or a leading ``~`` (an oblivious, pre-nullable-annotation
  reference type) before the dotted path.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHIPPED_PATH = REPO_ROOT / "csharp" / "src" / "VerdictRules" / "PublicAPI.Shipped.txt"
UNSHIPPED_PATH = REPO_ROOT / "csharp" / "src" / "VerdictRules" / "PublicAPI.Unshipped.txt"

# Leading tokens the analyzer prints before a member's dotted path to record
# a modifier that affects binary/source compatibility. Longest-checked-first
# doesn't matter here -- none is a prefix of another -- but kept as a tuple
# (not a set) so the order in error messages / debugging stays deterministic.
_MODIFIER_PREFIXES = ("abstract ", "virtual ", "override ", "static ", "sealed ")

# Marks a reference type that predates this file's own `#nullable enable`
# annotation sweep (RS0041/RS0037) -- a formatting detail of the entry, not
# part of the dotted symbol path itself.
_OBLIVIOUS_PREFIX = "~"

# A *REMOVED* entry in PublicAPI.Unshipped.txt records a symbol's departure
# from the public surface for the next release's changelog -- it is already
# gone, so it is not part of what extract_symbols() reports as currently public.
_REMOVED_PREFIX = "*REMOVED*"

# A property or indexer accessor's dotted path ends in one of these instead
# of a member name on its own -- stripped to recover the property's own name.
_ACCESSOR_SUFFIXES = (".get", ".set")


def _strip_modifier_prefix(line: str) -> str:
    """Remove a leading compatibility-modifier token, if this line has one."""
    for prefix in _MODIFIER_PREFIXES:
        if line.startswith(prefix):
            return line[len(prefix) :]
    return line


def _strip_generic_arity(type_name: str) -> str:
    """Collapse an open generic's ``<T>`` suffix so ``AndRule<TContext>`` and
    ``AndRule`` -- the dict-context closed specialization and the generic
    type it wraps -- normalize to the same concept-map type name ``AndRule``,
    matching how api-concepts.yaml records one row per concept regardless of
    which specialization a language-specific snapshot actually declares it on.
    """
    arity_start = type_name.find("<")
    return type_name if arity_start == -1 else type_name[:arity_start]


def _parse_line(line: str) -> dict[str, str | None] | None:
    """Parse one PublicAPI.txt line into a normalized ``{type, member}`` row.

    Returns ``None`` for a line that carries no symbol of its own (blank, a
    ``#nullable`` header, or a ``*REMOVED*`` entry).
    """
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or stripped.startswith(_REMOVED_PREFIX):
        return None

    stripped = _strip_modifier_prefix(stripped)
    if stripped.startswith(_OBLIVIOUS_PREFIX):
        stripped = stripped[len(_OBLIVIOUS_PREFIX) :]

    # A member line carries " -> ReturnType"; a bare type declaration doesn't.
    signature, separator, _return_type = stripped.partition(" -> ")
    if not separator:
        dotted_path = _strip_generic_arity(signature)
        *_namespace, type_name = dotted_path.split(".")
        return {"type": type_name, "member": None}

    # A property/indexer accessor ends in ".get"/".set" instead of "(...)".
    for accessor_suffix in _ACCESSOR_SUFFIXES:
        if signature.endswith(accessor_suffix):
            signature = signature[: -len(accessor_suffix)]
            break
    else:
        # A method or constructor -- cut the "(params)" portion to recover
        # the bare dotted path.
        signature = signature.split("(", 1)[0]

    *namespace_and_type, member_name = signature.split(".")
    *_namespace, type_name = namespace_and_type
    return {"type": _strip_generic_arity(type_name), "member": member_name}


def _parse_file(path: Path) -> list[dict[str, str | None]]:
    """Parse every symbol row out of one committed PublicAPI.*.txt file."""
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        row = _parse_line(line)
        if row is not None:
            rows.append(row)
    return rows


def extract_symbols() -> list[dict[str, str | None]]:
    """Return every public symbol in the package's committed snapshot, normalized.

    Each item is a dict: {'type': 'TypeName', 'member': 'MemberName' or None}.
    member=None means the row describes the type itself (a type-level
    concept with no further member, matching api-concepts.yaml's own
    member: '' rows). Reads the COMMITTED snapshot file on disk --
    does not invoke the language's own CLI tool itself (that already ran
    once to generate the committed file; this function just parses it).
    """
    rows = _parse_file(SHIPPED_PATH) + _parse_file(UNSHIPPED_PATH)

    # Collapsing an open generic and its dict-context closed specialization
    # onto one type name (AndRule<TContext> and AndRule both -> "AndRule")
    # legitimately produces the same {type, member} row from two distinct
    # PublicAPI.txt lines (most visibly every type-level declaration line,
    # member=None). Deduplicating here -- while preserving first-seen order,
    # since nothing downstream needs PublicAPI.txt's own line order -- keeps
    # the row count meaningful as "one row per distinct public symbol" rather
    # than "one row per PublicAPI.txt line that happens to describe it".
    seen: set[tuple[str, str | None]] = set()
    deduped = []
    for row in rows:
        key = (row["type"], row["member"])
        if key not in seen:
            seen.add(key)
            deduped.append(row)
    return deduped


if __name__ == "__main__":
    import json

    print(json.dumps(extract_symbols(), indent=2))
